config/routes.rb
Ijustdidit::Application.routes.draw do
  devise_for :users

  resources :locations
  resources :posts
  get 'tags/:tag', to: 'posts#show', as: :tag

   root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :post_id
  belongs_to :user
  belongs_to :post
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  address    :string(255)
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  style       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  address     :string(255)
#  latitude    :float
#  longitude   :float
#  user_id     :string(255)
#

class Post <  ActiveRecord::Base
   attr_accessible :recommendation, :title,:user_id,  :style, :description, :address, :location_id, :tag_list, :city, :state
   acts_as_taggable
   belongs_to :location 
   belongs_to :user
   validates :address, :title,:description, :presence => true
   geocoded_by :address
   after_validation :geocode, :if => :address_changed?
   paginates_per 10

   has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
  def index
    @locations = Location.all
  end


  def show
    location = Location.find(params[:id])
  end
 
  def  new
    @location = Location.new
  end 

  def create
    @location=Location.new(:location)

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :only=>[:new, :create, :edit]
  
  def index
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
  end
 
  def new
    @post = Post.new
  end 

  def create
    @post = Post.new(params[:post])

   if  @post.save
     redirect_to root_path
   else
     render :new
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ijustdidit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
      body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
                      }
                          </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%=link_to "I DID IT HERE!", posts_path, class: "brand"%>
            <div class="nav-collapse collapse">
              <p class="navbar-text pull-right">
  
  
              <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

              </p>
              <ul class="nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><%=link_to "New Post", new_post_path %></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>


      <div class="container">
        <%= yield %>
      </div>


</body>
</html>

app/views/posts/index.html.erb
<div class="container" >
    <%@posts.each do |post|%>
      <%=post.title %></br>
      <%=link_to post.address, post %></br>
    </br>
    <%end %>
</div>

app/views/posts/index.html.haml
-@posts.each do |post|
  =post.title
  %br
  =link_to post.address, post
  %br
  %p
  

app/views/posts/new.html.erb
<div class="container" >
<%=form_for @post do |f| %>
  <%=f.label  "Title" %>
  <%=f.text_field :title %></br>
  <%=f.label  "Positions" %>
  <%=f.text_field :tag_list %></br>
  <%=f.label  "Address" %>
  <%=f.text_field :address %></br>
  <%=f.label  "Description" %>
  <%=f.text_area :description, :size => "20x5"%></br>
  <%=f.submit "Submit" %>
<%end%>
</div>

app/views/posts/show.html.erb
<div class="container">
  <p>
  <h3> <%=@post.title %> </h3>
  <p>
  <strong> Positions</strong>: <i><%=link_to "#{@post.tag_list}", "" %></br></i>
  <p>
  <strong>Location</strong>:<i> <%=@post.address %></i></br>
  <p>
  <%=@post.description %></br>
  <p>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@post.latitude}%2C#{@post.longitude}" %>
<div >

app/views/posts/show.html.haml
%h3= @post.title 
%p
%strong
 Positions:
 %small= @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
%br 
%strong 
 =@post.address
%br 
=@post.description
%br
=image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@post.latitude}%2C#{@post.longitude}"